/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NcImg {
        "alt": string;
        "hasSize": boolean;
        "src": string;
        "srcset": string;
    }
}
declare global {
    interface HTMLNcImgElement extends Components.NcImg, HTMLStencilElement {
    }
    var HTMLNcImgElement: {
        prototype: HTMLNcImgElement;
        new (): HTMLNcImgElement;
    };
    interface HTMLElementTagNameMap {
        "nc-img": HTMLNcImgElement;
    }
}
declare namespace LocalJSX {
    interface NcImg {
        "alt"?: string;
        "hasSize"?: boolean;
        "src"?: string;
        "srcset"?: string;
    }
    interface IntrinsicElements {
        "nc-img": NcImg;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nc-img": LocalJSX.NcImg & JSXBase.HTMLAttributes<HTMLNcImgElement>;
        }
    }
}
